//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NassquaDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB_A1EA14_nassquaCoreEntities : DbContext
    {
        public DB_A1EA14_nassquaCoreEntities()
            : base("name=DB_A1EA14_nassquaCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ExperienceSet> ExperienceSets { get; set; }
    
        public virtual ObjectResult<HZ_ExperienceSet_CRUD_Result> HZ_ExperienceSet_CRUD(string op, string expId, string expDesc)
        {
            var opParameter = op != null ?
                new ObjectParameter("Op", op) :
                new ObjectParameter("Op", typeof(string));
    
            var expIdParameter = expId != null ?
                new ObjectParameter("ExpId", expId) :
                new ObjectParameter("ExpId", typeof(string));
    
            var expDescParameter = expDesc != null ?
                new ObjectParameter("ExpDesc", expDesc) :
                new ObjectParameter("ExpDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HZ_ExperienceSet_CRUD_Result>("HZ_ExperienceSet_CRUD", opParameter, expIdParameter, expDescParameter);
        }
    }
}
