//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NassquaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienceSet
    {
        public int ExpId { get; set; }
        public string ExpDesc { get; set; }
    }
}
