//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NassquaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ResId { get; set; }
        public Nullable<int> ResUserId { get; set; }
        public Nullable<int> ResScheId { get; set; }
        public Nullable<int> ResNoPeople { get; set; }
        public Nullable<decimal> ResTotal { get; set; }
        public Nullable<System.DateTime> ResDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
