//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NassquaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int ScheId { get; set; }
        public Nullable<int> ScheExpId { get; set; }
        public Nullable<System.DateTime> ScheDate { get; set; }
        public Nullable<int> ScheNoPeople { get; set; }
        public Nullable<decimal> ScheUnitCost { get; set; }
    
        public virtual Experience Experience { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
