//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NassquaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int UserId { get; set; }
        public string UserIdCard { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public Nullable<int> UserAge { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
    
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
